### ISSUE TITLE
Add natural language processing to date queries

### ISSUE THREAD

**Issue by thakichowdhury** [tgrosinger/tq-obsidian#10]
**Is your feature request related to a problem? Please describe.**
I like to keep my task list on my daily note, filtered by those due that day and priority levels (e.g. P1, P2,...PN). Currently, with tq, the only way I can see to filter for tasks due that day is to manually input the current date each day in the filter query.

**Describe the solution you'd like**
Being able to describe dates in the query using natural language, such as `select-day: today`, would mean that I could just put that generic query in my daily notes template and not have to adjust the query each day.

**Describe alternatives you've considered**
I've considered having a single page that represents the overall status of my task list, demarcated by days similar to the examples in the README. The reason I prefer not to do this is because I like to keep my tasks relatively isolated from each other so that I can just _focus_ on the tasks at hand and not feel overwhelmed by those due before or after. Think of it as separation of concerns.

**Additional context**
Here is my current workflow with an alternative task management system. tq has, in my opinion, a much cleaner UI and I **love** certain features like the use of the calendar for date selection.

![image](https://user-images.githubusercontent.com/4053163/125141003-a7e7cf00-e0c8-11eb-9625-d8e7964ab322.png)

**Comment by tgrosinger** [comment]
Thanks for the suggestion. My interpretation is that "today" would refer to the day of the daily note, if the block is in a daily note. It does however introduce undefined behavior if the code block is not on a daily note, or if the daily note naming format is unrecognized.

I'm going to leave this open, however it probably won't be something I am able to add for a while. In the mean time, what I do is use a variable in my template:

    ```tq
    select-day: {{date}}
    overdue: true
    completed: false
    ``` 

When I create my daily note by clicking on a day in the [Calendar plugin](https://github.com/liamcain/obsidian-calendar-plugin) it will fill in the template for me. I am not using the templater plugin, just Calendar.

**Comment by thakichowdhury** [comment]
Ah, that sounds like a great idea. Thanks!
