### ISSUE TITLE
Take advantage of nested tags

### ISSUE THREAD

**Issue by jebeaudoin** [tgrosinger/tq-obsidian#15]
**Is your feature request related to a problem? Please describe.**
Obsidian's nested tags create meaningful hierarchies. It would be helpful to be able to create higher-level views in tq. For example, I like being able to view tasks related to "#PROJECT/A." I like being able to view tasks related to "#PROJECT/B." But for weekly and monthly planning and review, it would be important to view tasks related to #Project and see tasks related to both A and B. Of course, I can add multiple tags, but the process would become burdensome quite quickly (I have 47 waiting or active projects in my portfolio right now).

**Describe the solution you'd like**
Enable tq to use nested tags hierarchically.

**Describe alternatives you've considered**
The only alternatives I've considered would wreak havoc on tags (e.g. tagging all projects with "#PROJECTS" as well as their specific project tag, because this would have to be replicated for all other categories of hierarchical tags as well).

**Additional context**

**Comment by tgrosinger** [comment]
@jebeaudoin, that sounds like a great idea. I'll see what I can do.

And thank you very much for the generous support!

**Comment by tgrosinger** [comment]
Doesn't look like Obsidian exposes tags in a nested format natively, so I'll have to parse them and do string comparison myself. Should be achievable though.

**Comment by tgrosinger** [comment]
This will be in the next release.
