### ISSUE TITLE
Completed property does not filter correctly on 'true" value

### ISSUE THREAD

**Issue by jebeaudoin** [tgrosinger/tq-obsidian#16]
**Describe the bug**
The completed property does not filter on 'true" value

**To Reproduce**
1. Edit a note and...
    a. Create simple tq custom block with "completed: true"
    b. Create simple tq custom block with "completed: false"
    c. Create simple tq custom block with "completed: "
2. Preview note...

**Expected behavior**
Case 1 ("completed: true") - Fails
EB (expected behavior) - List of completed tasks
AB (actual behavior) - List of all tasks

Case 2 ("completed: false") - Succeeds
EB - List of incomplete tasks
AB - List of incomplete tasks

Case 3 ("completed: ") - Default (per documentation) fails
EB (expected behavior) - List of complete tasks
AB (actual behavior) - List of incomplete tasks

**Screenshots**
<img width="414" alt="Bug Report S1" src="https://user-images.githubusercontent.com/10992411/126069117-4918ceb3-2878-491f-a604-0d67aa8c8cee.png">
---
<img width="413" alt="Bug Report S2" src="https://user-images.githubusercontent.com/10992411/126069124-f636d059-f7c7-440d-a4ff-39d7af455082.png">

**Desktop (please complete the following information):**
 - OS: [Mac OS v11.4]
 - Obsidian Version: [e.g. v0.12.10]
 - tq Version: [0.2.0] 
 
**Additional context**
I think this worked in an earlier version.

**Comment by tgrosinger** [comment]
This will be in the next release.

**Comment by jebeaudoin** [comment]
That was lightning fast! Thanks!
