### ISSUE TITLE
Plugin won't run

### ISSUE THREAD

**Issue by isle99** [tgrosinger/tq-obsidian#2]
**Describe the bug**
This is what I get in the console when I try to turn the plugin on:
Plugin failure: tq-obsidian Error: ENOENT: no such file or directory, open '...\Obsidian\brainforest\\.obsidian\plugins\tq-obsidian-0.0.1\main.js'

**To Reproduce**
/

**Expected behavior**
/

**Screenshots**
/

**Desktop (please complete the following information):**
 - OS: Windows
 - Obsidian Version: v0.12.5
 - tq Version: 0.0.1

**Additional context**
/
/

**Comment by tgrosinger** [comment]
Please make sure you have that `main.js` mentioned in the error message in that directory. You can download it from the release page.

https://github.com/tgrosinger/tq-obsidian/releases/tag/0.0.1

**Comment by isle99** [comment]
Works now. I've uhmm, missed that somehow.
