### ISSUE TITLE
Tasks without due date unexpectedly included in list

### ISSUE THREAD

**Issue by jebeaudoin** [tgrosinger/tq-obsidian#20]
**Describe the bug**
According to the documentation, the following codeblock should create a list of uncompleted tasks due today or which are overdue.
```tq
select-day: 2021-06-06
completed:  false
overdue:    true
```
However, changing only the select-day property to the current date, the block generates a list of all uncompleted tasks, including those without any date.

**To Reproduce**
Copy and paste the code block into an Obsidian note. Change the date. Go to Preview mode.

**Expected behavior**
I expected to see a list that only contained overdue or currently due uncompleted dates.

**Screenshots**
See attached...
![Screen Shot 2021-07-21 at 2 43 39 PM](https://user-images.githubusercontent.com/10992411/126542984-c6effad2-17df-4415-8808-f50d296cd2bd.png)

**Desktop (please complete the following information):**
- OS: [Mac OS v11.4]
- Obsidian Version: [e.g. v0.12.11]
- tq Version: [0.4

**Additional context**

**Comment by tgrosinger** [comment]
@jebeaudoin, please add `no-due: false` to your filter. Let me know if that fixes it for you.

**Comment by jebeaudoin** [comment]
Yes, that resolves the issue. Thanks!
