### ISSUE TITLE
Query tasks with Dataview

### ISSUE THREAD

**Issue by RadionAtl** [tgrosinger/tq-obsidian#21]
I would like to use the dataview plugin to create a table of tasks so I can see most of the attributes of the Tq task files.  Can can the field name for the task in the tq files be exposed to enable this approach?

**Comment by tgrosinger** [comment]
I'm not sure what you mean by exposing the task field name. The tasks are the first task line of the note after the frontmatter. Let me know if that doesn't answer the question for you.

**Comment by RadionAtl** [comment]
After some additional research, I see that my goal is not achievable with Dataview.  I had hoped to have the task checkbox return in a Dataview table query, the same as is available in the Dataview list query; similar to the Tq query but with more metadata available in the resulting visual.
Thank you for such a quick reply.  I love the plug-in.
Cheers.
