### ISSUE TITLE
Add file created listener

### ISSUE THREAD

**Issue by jebeaudoin** [tgrosinger/tq-obsidian#22]
Hi,

I've created a Zapier recipe to create a task note from my browser that captures the active web page title and url. Everything is working fine, but I am facing one "inconvenience" and I'm not sure if it can be addressed.

It appears that if a task is created manually in Obsidian (or via my Zap) -- that is, not using the TQ ribbon interface or palette commands -- the plugin won't "register" the task until either the note content changes (by adding a character) or until the plugin reloads when Obsidian is closed and relaunched.

Since I'm not a coder, I can't even begin to imagine how the plugin works, but it does seem to monitor a task note's last modified date value. Is there an easy way to monitor for the "unexpected arrival" of a new note in the designated task folder?

Thanks,
Jack

**Comment by tgrosinger** [comment]
I should be able to hook that up. Right now I'm only listening for the `modified` event, but I can add a listener for the `create` event as well.

In the mean time, you should also take a look at the [section in the readme](https://github.com/tgrosinger/tq-obsidian#creating-tasks) about creating tasks using the `obsidian://` url scheme. That's what I am using for iOS shortcuts to create tasks.
