### ISSUE TITLE
Completed tasks from previous days are shown when overdue is true

### ISSUE THREAD

**Issue by ganser8** [tgrosinger/tq-obsidian#23]
If I specify today date `select-day: 2021-07-26`, why I see completed yesterday tasks? I want to see tasks I done today only. How to do that?

**Comment by tgrosinger** [comment]
By default tasks with no due date are included, even when using `select-day`.

Please try a query like this:

    ```tq
    select-day: 2021-07-26
    no-due: false
    ```

You may also add `completed: false` if you would like to only include unchecked tasks.

**Comment by ganser8** [comment]
I want to see checked and unchecked today's tasks only. But I also see yesterday's checked tasks that have `due: 2021-07-25`. It seems it's because of `overdue: true`. Are yesterday's completed tasks overdue? I thought only unchecked tasks are overdue. Is there a way to see checked and unchecked today's tasks + overdue but not checked tasks?

```
---
due: '2021-07-26'
---

- [ ] today's task
```

```
---
due: '2021-07-25'
---

- [x] yesterday's task
```

```
```tq
select-day: 2021-07-26
overdue: true
```

**Comment by ganser8** [comment]
I don't know why, but in 0.5.0 when I click on a checkbox it remains unchecked

**Comment by tgrosinger** [comment]
Oh you're right. I am guessing that putting that class on the checkbox makes it so Obsidian tries to handle the checkbox and steps on my event listener. I will have to remove that class again.

**Comment by ganser8** [comment]
Looks like there is the same problem with `select-week`. If I have `overdue: true` I see the completed tasks for all time.
