### ISSUE TITLE
Task UI

### ISSUE THREAD

**Issue by RadionAtl** [tgrosinger/tq-obsidian#26]
**Is your feature request related to a problem? Please describe.**

> Having a single panel for all tasks with the ability to add a new task would be incredibly helpful to my workflow.
   

**Describe the solution you'd like**

> There is a UI in your [usage gif](https://raw.githubusercontent.com/tgrosinger/tq-obsidian/main/resources/screenshots/tq-demo.gif) (see the 42.31 seconds mark).  In it, you have a 'create new task' function which pairs well with the one-click 'add panel' functionality which will work well in my workflow. 
Will you be releasing the UI sometime in the future?

**Describe alternatives you've considered**

> I have created multiple views using the plug-in queries, setup hotkeys and created data view tables.  My next step is to play with the url option outlined in the plug-in documentation. 

**Additional context**

**Comment by tgrosinger** [comment]
Hello, thank you for the suggestion.
The old UI in that gif has been removed from this plugin, but no functionality was removed. That was just a view that showed a normal query, you just couldn't edit that query.

I think this will show you all the tasks:

    ```tq
    ```
