### ISSUE TITLE
Custom blocks don't seem to be rendering

### ISSUE THREAD

**Issue by bzupnick** [tgrosinger/tq-obsidian#3]
**Describe the bug**
The custom blocks are just rendering as a code block where the query is shows as code. For example this: 
![image](https://user-images.githubusercontent.com/982253/123681333-b35d0f80-d817-11eb-9b21-98ccb14d805a.png)
looks like the following in viewing mode: 
![image](https://user-images.githubusercontent.com/982253/123681374-c1ab2b80-d817-11eb-9380-8aff73ed7e53.png)

**To Reproduce**
1. Create any custom block
2. view it in viewing mode

**Expected behavior**
Expected behavior is to see the tasks that the query produces in `viewing mode`

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Obsidian Version: v0.12.8
 - tq Version: 0.0.2

**Additional context**

**Comment by tgrosinger** [comment]
This feature is not released yet. Coming soon :)

**Comment by bzupnick** [comment]
Ha. That explains it! I was REALLY trying to figure out what I was doing wrong!

Thanks for all the work, and feel free to hit me up if you need another tester!

**Comment by tgrosinger** [comment]
Will, do. I appreciate the offer, thanks.
