### ISSUE TITLE
Template for new TQ notes

### ISSUE THREAD

**Issue by liam5463** [tgrosinger/tq-obsidian#33]
**Is your feature request related to a problem? Please describe.**
ability to add custom metadata to tasks

**Describe the solution you'd like**
ability to add custom metadata to tasks

**Describe alternatives you've considered**
template for new tq notes?
option to add custom metadata

**Additional context**

**Comment by tgrosinger** [comment]
Hi @liam5463, I think this is a duplicate of #18.
